### ISSUE TITLE
Filter distances based on prior knowledge of attitude

### ISSUE THREAD

**Issue by taldcroft** [sot/find_attitude#22]
We have thought of two ways to filter:
- a radial filter around an attitude
- a band in sun pitch

This issue is coupled with the ability to reduce the number of stars required to find a match (down to three).

Reducing the requirement to just two stars would require larger changes to find_attitude, such as filtering on the roll between the two stars, or their magnitude difference.

**Comment by jeanconn** [comment]
Closed by #31
